export const marketplaceOffers = [
  {
    id: 1, eyebrow: 'AI TRANSFORMATION', title: 'Enterprise AI Signal Pack', description: 'A continuously refreshed intelligence brief, benchmark library, and executive decision kit for AI leaders.', category: 'AI & Digital', format: 'Annual access', price: 8400, tone: 'lime', badge: 'Most selected',
  },
  {
    id: 2, eyebrow: 'EXECUTIVE WORKSHOP', title: 'AI Value Realization Sprint', description: 'A four-week working session to identify value pools, pressure-test use cases, and leave with a funded roadmap.', category: 'AI & Digital', format: '4-week sprint', price: 42000, tone: 'violet', badge: 'BCG expert-led',
  },
  {
    id: 3, eyebrow: 'CLIMATE & SUSTAINABILITY', title: 'Transition Advantage Lens', description: 'Market scenarios, emissions benchmarks, and a board-ready playbook tailored to your sector and geography.', category: 'Climate', format: 'Enterprise license', price: 14800, tone: 'mint',
  },
  {
    id: 4, eyebrow: 'OPERATIONS', title: 'Procurement Advantage Suite', description: 'Category intelligence, should-cost models, supplier signals, and governance workflows for procurement teams.', category: 'Operations', format: 'Team license', price: 26400, tone: 'amber',
  },
  {
    id: 5, eyebrow: 'CONSUMER INSIGHTS', title: 'Demand Spaces Explorer', description: 'Explore category demand, consumer tensions, and growth spaces with an interactive decision cockpit.', category: 'Consumer', format: '90-day access', price: 12600, tone: 'coral',
  },
  {
    id: 6, eyebrow: 'ORGANIZATION STRATEGY', title: 'Future-Ready Organization Lab', description: 'A modular leadership experience for redesigning work, capabilities, and decision rights in the AI era.', category: 'Organization', format: 'Leadership cohort', price: 36000, tone: 'blue',
  },
];

export const bcgSolutions = [
  {
    id: 101,
    slug: 'marketplace-accelerator',
    code: 'MX',
    name: 'Marketplace Accelerator by BCG X',
    shortName: 'Marketplace Accelerator',
    category: 'Growth',
    tone: 'lime',
    metric: 'AI-powered',
    metricLabel: 'launch, scale, and optimization',
    url: 'https://www.bcg.com/x/product-library/marketplace-accelerator-by-bcg-x',
    description: 'AI-powered services that accelerate marketplace launches, drive scale, optimize seller performance, and grow GMV.',
    longDescription: 'Marketplace Accelerator is a series of AI-powered services for launching a new marketplace proposition or expanding an existing one. It combines buyer experience, seller performance, and operations into one value-led transformation path.',
    capabilities: [['Marketplace strategy', 'Define the proposition, operating model, and value pools that make the marketplace worth building.'], ['Buyer experience', 'Apply AI-driven discovery and personalization to improve relevance, conversion, and loyalty.'], ['Seller acceleration', 'Improve onboarding, selection quality, pricing, and seller performance with data-led workflows.'], ['Operations cockpit', 'Connect marketplace health, GMV performance, and execution signals in a single operating view.']],
    outcomes: ['Faster proposition launch', 'Improved seller performance', 'More relevant buyer journeys', 'Scalable marketplace operations'],
    deployment: ['Marketplace diagnostic', 'Value-pool prioritization', 'Configured accelerator services', 'Scale and transfer roadmap'],
  },
  {
    id: 102,
    slug: 'data-intelligence-ai',
    code: 'DI',
    name: 'Data Intelligence AI by BCG X',
    shortName: 'Data Intelligence AI',
    category: 'Growth',
    tone: 'violet',
    metric: '$10B',
    metricLabel: 'unlocked across 200+ clients',
    url: 'https://www.bcg.com/x/product-library/data-intelligence-ai',
    description: 'A data-to-solutions accelerator combining proprietary models, external datasets, and AI decision intelligence.',
    longDescription: 'Data Intelligence AI combines an organization’s data with external datasets and AI decision-making to uncover customers, trends, and opportunities. Its modular ecosystem is designed to expand as data maturity and ambition grow.',
    capabilities: [['B2B intelligence', 'Identify leads, white spaces, and sharper choices for what to sell, where to play, and how to price.'], ['Customer 360', 'Connect fragmented customer data into a richer, actionable view across channels and accounts.'], ['Data marketplace', 'Create self-service access to governed data and AI assets through a build-operate-transfer model.'], ['Secure clean rooms', 'Enable privacy-compliant joint analysis without compromising sensitive customer or partner data.']],
    outcomes: ['Faster commercial decisions', 'New growth white spaces', 'Secure data collaboration', 'Reusable intelligence assets'],
    deployment: ['Data landscape review', 'Priority-use-case sprint', 'Model and dataset configuration', 'Adoption and transfer plan'],
  },
  {
    id: 103,
    slug: 'deep-customer-engagement-ai',
    code: 'CX',
    name: 'Deep Customer Engagement AI by BCG X',
    shortName: 'Deep Customer Engagement AI',
    category: 'Growth',
    tone: 'coral',
    metric: 'Up to 40%',
    metricLabel: 'more customer lifetime value',
    url: 'https://www.bcg.com/x/product-library/deep-ai-powered-customer-management',
    description: 'Hyperpersonalized, end-to-end customer management that delivers real-time, AI-driven recommendations at scale.',
    longDescription: 'Deep Customer Engagement AI integrates artificial intelligence into customer interactions to deliver real-time recommendations. BCG X pairs the technology with data foundations, campaign activation, and capability transfer.',
    capabilities: [['Next-best action', 'Generate real-time recommendations for acquisition, retention, cross-sell, and service moments.'], ['Customer decisioning', 'Coordinate models, business rules, and eligibility in a scalable decision layer.'], ['Journey activation', 'Embed recommendations across human and digital channels with closed-loop measurement.'], ['AI-enabled operating model', 'Establish teams, workflows, and governance that sustain personalization at scale.']],
    outcomes: ['Higher customer acquisition', 'More cross-sell and upsell', 'Reduced churn', 'Stronger price realization'],
    deployment: ['Customer-value diagnostic', 'Use-case portfolio', 'Pilot campaigns and models', 'Industrialization roadmap'],
  },
  {
    id: 104,
    slug: 'supply-chain-ai',
    code: 'SC',
    name: 'Supply Chain AI by BCG X',
    shortName: 'Supply Chain AI',
    category: 'Operations',
    tone: 'mint',
    metric: '2–4pp',
    metricLabel: 'potential EBITDA boost',
    url: 'https://www.bcg.com/x/product-library/supply-chain-ai',
    description: 'A modular digital supply-chain offering spanning network design, planning, resilience, control towers, and logistics.',
    longDescription: 'Supply Chain AI combines digital assets, supply-chain expertise, and data science to transform strategy, design, planning, and execution. Specialized modules can be combined around the highest-value constraints and opportunities.',
    capabilities: [['Network design', 'Optimize the footprint, flows, inventory allocation, and transportation choices across the network.'], ['End-to-end planning', 'Connect demand, supply, and financial planning with AI-supported decisions and scenarios.'], ['Digital twin', 'Model the value chain to test tradeoffs, predict disruption, and improve operational response.'], ['Control tower', 'Create cross-functional visibility, prioritized alerts, and orchestration across execution teams.']],
    outcomes: ['Lower supply-chain costs', 'Improved service levels', 'Reduced working capital', 'Lower near-term emissions'],
    deployment: ['Rapid diagnostic', 'Value and feasibility case', 'Modular solution configuration', 'Scale and capability transfer'],
  },
  {
    id: 105,
    slug: 'frontline-ops-ai',
    code: 'FO',
    name: 'Frontline Ops AI by BCG X',
    shortName: 'Frontline Ops AI',
    category: 'Operations',
    tone: 'amber',
    metric: '5%+',
    metricLabel: 'labor productivity gains',
    url: 'https://www.bcg.com/x/product-library/frontline-ops-ai',
    description: 'An AI platform connecting labor, inventory, scheduling, and frontline workflows to improve execution at scale.',
    longDescription: 'Frontline Ops AI connects data, business rules, AI agents, and human decision-makers across labor, inventory, and field workflows. It is designed to improve execution without requiring a full technology replacement.',
    capabilities: [['Labor optimization', 'Forecast demand, build healthier rosters, and align schedules to business and employee needs.'], ['Inventory flow', 'Improve availability, surface root causes, and target interventions that protect working capital.'], ['Workforce assistant', 'Place answers, recommendations, alerts, and task support inside everyday frontline workflows.'], ['Agentic orchestration', 'Coordinate decisions across systems, rules, AI agents, and accountable human operators.']],
    outcomes: ['Higher labor productivity', 'Lower employee turnover', 'Fewer schedule edits', 'Better frontline execution'],
    deployment: ['Operational baseline', 'Workflow and data review', 'Product-module pilot', 'Site rollout roadmap'],
  },
  {
    id: 106,
    slug: 'smart-banking-ai',
    code: 'BK',
    name: 'Smart Banking AI by BCG X',
    shortName: 'Smart Banking AI',
    category: 'Industry AI',
    tone: 'blue',
    metric: '20–30%',
    metricLabel: 'potential profit boost',
    url: 'https://www.bcg.com/x/product-library/ai-in-financial-services',
    description: 'A unified customer-intelligence platform that equips relationship managers with high-value leads and next-best actions.',
    longDescription: 'Smart Banking AI consolidates customer information into a unified platform and applies AI to help banks serve the right customer with the right action. It connects insight generation directly to relationship-manager workflows.',
    capabilities: [['Generative AI', 'Draft personalized outreach, summarize reports, and create investment or relationship-management memos.'], ['Next-best solution', 'Reveal changing customer needs and identify products or services most likely to resonate.'], ['Retention', 'Spot churn signals early and prompt proactive, prioritized relationship actions.'], ['Risk monitoring', 'Segment reviews into appropriate lanes to reduce cost while preserving analytical rigor.']],
    outcomes: ['Deeper customer relationships', 'Higher-value lead generation', 'Reduced churn', 'Lower review costs'],
    deployment: ['Banking-data assessment', 'Priority journey selection', 'Relationship-manager pilot', 'Scaled operating model'],
  },
  {
    id: 107,
    slug: 'retail-ai',
    code: 'RT',
    name: 'Retail AI by BCG X',
    shortName: 'Retail AI',
    category: 'Industry AI',
    tone: 'lime',
    metric: '6',
    metricLabel: 'value-chain components',
    url: 'https://www.bcg.com/x/product-library/retail-ai',
    description: 'Tailored retail intelligence spanning pricing, merchandising, supply chain, operations, and customer engagement.',
    longDescription: 'Retail AI is a tailored portfolio of retail intelligence solutions that integrates into existing technology and data environments. Modules target the highest-value opportunities across the retail value chain.',
    capabilities: [['Merchandising', 'Improve assortment, space, allocation, and merchant decisions through flexible analytics applications.'], ['Pricing and promotion', 'Optimize price, promotion, and revenue decisions against demand and competitive signals.'], ['Store operations', 'Connect labor, inventory, and store workflows to drive more consistent frontline execution.'], ['Customer engagement', 'Use customer data and AI decisioning to improve relevance throughout the retail journey.']],
    outcomes: ['Stronger assortment decisions', 'More productive operations', 'Improved availability', 'More relevant customer experiences'],
    deployment: ['Retail value diagnostic', 'Module selection', 'Data and workflow integration', 'Enterprise rollout plan'],
  },
  {
    id: 108,
    slug: 'revenue-growth-management-ai',
    code: 'RG',
    name: 'Revenue Growth Management AI by BCG X',
    shortName: 'Revenue Growth Management AI',
    category: 'Industry AI',
    tone: 'violet',
    metric: 'At scale',
    metricLabel: 'commercial decision support',
    url: 'https://www.bcg.com/x/product-library/revenue-growth-management-ai',
    description: 'An AI-powered platform that helps consumer-goods companies operationalize revenue growth management at scale.',
    longDescription: 'Revenue Growth Management AI helps consumer-goods organizations embed sharper commercial decisions into core workflows. BCG X configures the platform to the business and connects analytics with everyday execution.',
    capabilities: [['Pricing', 'Build consistent, evidence-led pricing choices across products, channels, and markets.'], ['Promotion', 'Improve promotion design, evaluation, and investment decisions with granular analytics.'], ['Trade investment', 'Allocate commercial resources to the customers and activities with the strongest value case.'], ['Workflow activation', 'Place recommendations into the planning and execution moments where teams make decisions.']],
    outcomes: ['Better price realization', 'More productive promotions', 'Sharper trade allocation', 'Repeatable RGM workflows'],
    deployment: ['RGM maturity review', 'Value-driver prioritization', 'Configured platform pilot', 'Process and capability rollout'],
  },
];

export const agendaItems = [
  ['13:00', 'Part 1', 'Framing and taxonomy', 'What we are answering, and the vocabulary, before any capability is named.', '6 min', 'Jenifer Hanki'],
  ['13:06', '2.1', 'Large, complex catalogs and AI discoverability', 'Live plus back end.', '14 min', 'Jenifer Hanki'],
  ['13:20', '2.2', 'Personalisation, dynamic content and experience delivery', 'Live plus back end.', '12 min', 'Jenifer Hanki'],
  ['13:32', '2.3', 'B2B depth and procurement governance', 'Live plus back end.', '10 min', 'Jenifer Hanki'],
  ['13:42', '2.4', 'Speed to market, extensibility and agentic development', 'Back end plus framework.', '10 min', 'Jenifer Hanki'],
  ['13:52', '3.1', 'Agentic commerce: architecture, status and governance', 'Framework plus live.', '12 min', 'Jenifer Hanki'],
  ['14:04', '3.2', 'Scale, reliability and honest limits', 'Framework.', '7 min', 'Jenifer Hanki'],
  ['14:11', 'Part 4', 'Recommendations and next steps', 'Discussion.', '8 min', 'Jenifer Hanki and Juan Trinidad'],
  ['14:19', 'Q&A', 'Questions', 'Held deliberately, not borrowed from earlier blocks.', '8 min', 'All'],
  ['14:27', 'Close', 'Close and agreed next step', 'Decision and owners.', '3 min', 'Juan Trinidad'],
];

export const getSolution = (slug) => bcgSolutions.find((solution) => solution.slug === slug);

export const formatCurrency = (value) => new Intl.NumberFormat('en-US', {
  style: 'currency', currency: 'USD', maximumFractionDigits: 0,
}).format(value);
